{% set name = "climlab-sbm-convection" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/climlab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 0852a75dbe8c486a302efb02cf56b776863d48fd446f498702e46a0ea7e9dc90

build:
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<311 or win]  
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
  host:
    - meson-python
    - python
    - numpy
    - pip
  run:
    - python
    - numpy

test:
  requires:
    - pytest
  imports:
    - climlab_sbm_convection
  commands:
    - pytest -v --pyargs climlab_sbm_convection

about:
  home: https://github.com/climlab/climlab-sbm-convection
  summary: 'Standalone Python wrapper for the Simplified Betts-Miller moist convection model'
  description: |
    climlab-sbm-convection makes the Frierson Simplified Betts-Miller convection code callable from Python by wrapping using f2py. This is a lightweight wrapper that emulates the Fortran interface as closely as possible. The primary use case is to drive the convection process in climlab, but it can be used as a standalone driver if you are familiar with the Fortran interface.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/climlab/climlab-sbm-convection

extra:
  recipe-maintainers:
    - brian-rose
